s3FileProcessingLambda:
  handler: src/handlers/s3FileProcessingLambda.handler
  environment:
    DYNAMODB_TABLE_NAME: !Ref S3ProcessTable
  role:
    Fn::GetAtt:
      - processS3BucketDetailsRole
      - Arn
  events:
    - s3:
        bucket: !Ref ProcessS3Bucket
        event: s3:ObjectCreated:*
        existing: true
    - s3:
        bucket: !Ref ProcessS3Bucket
        event: s3:ObjectRemoved:*
        existing: true
